### ISSUE TITLE
Works on Victus 16 3060, 5800H

### ISSUE THREAD

**Issue by Malya03** [iamSlightlyWind/HP-Victus-16-nbfc#1]
Works on HP VICTUS 16-E0504NW 4H3L7EA.

Arch Linux, nbfc builded by AUR package.

**Comment by Malya03** [comment]
Tested on that AUR package: https://aur.archlinux.org/packages/nbfc-linux

**Comment by iamSlightlyWind** [comment]
Yes, the models are similar. I just modify the curve to suit my need, as the curve on their repo is too aggressive for my specs, and Linux just refuses to ramp up the fans.

Closing this now.
